// ZipMaster configuration 1.9.2.x
// Configuration options - rebuild if changed

// Edwin: Enabled STATIC_LOAD_DELZIP_DLL to statically load DelZip192.dll because dynamically loading will
// hang MV (my app)
//__ STATIC_LOAD_DELZIP_DLL - define to statically load dll
{$DEFINE STATIC_LOAD_DELZIP_DLL}

//__ SUPPORT_OLD_WINDOWS - define if must run on Windows (95?),98,ME
//{$DEFINE SUPPORT_OLD_WINDOWS}


